---
title: "Pull sample of includes for methods typology"
author: "O'Hara"
format: 
  html:
    code-fold: true
    embed-resources: true
execute:
  echo: true
  warning: false
  message: false
editor: source
---

```{r setup}
library(tidyverse)
library(here)

```

# Summary

Select 60 or so included docs to review for refining a typology for the social science methods.

```{r}
ft_df <- read_csv(here('_data/screened_fulltext/ft_consolidated.csv'))

ft_by_method <- ft_df %>%
  mutate(method = str_split(econ_method, ';|/| and |\\?|,| informed by ')) %>%
  unnest(method) %>%
  mutate(method = str_squish(method)) %>%
  mutate(method = case_when(str_detect(method, 'cost.benefit') ~ 'cost-benefit assessment',
                            str_detect(method, 'survey') ~ 'survey',
                            str_detect(method, 'expert') ~ 'expert elicitation',
                            TRUE ~ method))

ft_sum <- ft_by_method %>%
  count(method)

assign_vec <- c('SB', 'SG', 'SR', 'BG', 'BR', 'GR') %>% rep(10)

set.seed(42)
ft_sample <- ft_by_method %>%
  group_by(method) %>%
  slice_sample(n = 3) %>%
  ungroup() %>%
  select(-method) %>%
  distinct() %>%
  slice_sample(n = 60) %>%
  mutate(assign = sample(assign_vec, replace = FALSE)) %>%
  mutate(Sam =      ifelse(str_detect(assign, 'S'), 'X', ''),
         Gillian =  ifelse(str_detect(assign, 'G'), 'X', ''),
         Becky =    ifelse(str_detect(assign, 'B'), 'X', ''),
         Rachelle = ifelse(str_detect(assign, 'R'), 'X', '')) %>%
  select(-assign)

write_csv(ft_sample, 'fulltext_sample_to_review.csv')
```

