---
title: "Gather full text results and consolidate"
author: "O'Hara"
format: 
  html:
    code-fold: true
    embed-resources: true
execute:
  echo: true
  warning: false
  message: false
editor: source
---

```{r setup}
library(tidyverse)
library(here)
```

# Summary

After all fulltext screening is complete, pull in the various fulltext results, consolidate, and analyze patterns

# Methods

## Consolidate fulltext results

```{r}
fs <- list.files(here('_data/screened_fulltext'), pattern = '^[0-9][a-z]?_fulltext_.+.csv$', full.names = TRUE)

key_df <- read_csv(here('_data/1c_refs_clean/ref_key_lookup.csv')) %>%
  mutate(title = tolower(title) %>% stringi::stri_trans_general('Latin-ASCII')) %>%
  select(title_match = title, key2 = key)

phases <- str_remove_all(basename(fs), '[0-9]_fulltext_|.csv')

df_all <- lapply(fs, read_csv, show_col_types = FALSE) %>% 
  setNames(phases) %>%
  bind_rows(.id = 'phase') %>%
  mutate(title_match = tolower(title) %>% stringi::stri_trans_general('Latin-ASCII')) %>%
  left_join(key_df, by = 'title_match')

df <- df_all %>%
  filter(screening_decision == 'include') %>%
  mutate(key = ifelse(is.na(key), key2, key)) %>%
  select(-screening_decision, -reason_for_exclusion, -revisited, -title_match, -key2)

write_csv(df, here('_data/screened_fulltext/ft_consolidated.csv'))
```
