---
title: "Sankey diagram of includes/excludes by phase"
author: "O'Hara"
format: 
  html:
    code-fold: true
    embed-resources: true
execute:
  echo: true
  warning: false
  message: false
editor: source
---

```{r setup}
library(tidyverse)
library(here)
library(networkD3)

```

# Summary

Sankey diagram of data access and cleaning prior to screening


```{r}
links <- tribble(
  ~source,                          ~target,                     ~value,
  'Soc Benefit Repo (n = 258)',  'Combined (n = 21,647)',           258,
  'Scopus (n = 18,585)',         'Combined (n = 21,647)',         13250,
  'Web of Science (n = 9,488)',  'Combined (n = 21,647)',          8139,
  'Scopus (n = 18,585)',         'Missing info (n = 3,729)',       2932,
  'Web of Science (n = 9,488)',  'Missing info (n = 3,729)',        797,
  'Scopus (n = 18,585)',         'Conf abstr (n = 2,955)',         2403,
  'Web of Science (n = 9,488)',  'Conf abstr (n = 2,955)',          552,
  'Combined (n = 21,647)',       'De-duplicated (n = 15,522)',    15522,
  'Combined (n = 21,647)',       'Duplicates (n = 6,125)',         6125,
  'De-duplicated (n = 15,522)',  'Analysis set (n = 13,820)',     13820,
  'De-duplicated (n = 15,522)',  'Spurious matches (n = 1,702)',   1702) %>%
  arrange(value) %>%
  mutate(source = fct_inorder(source)) %>%
  group_by(source) %>%
  mutate(n = sum(value)) %>%
  ungroup()
 
# From these flows we need to create a node data frame: it lists every entities involved in the flow
nodes <- data.frame(
  name=c(as.character(links$source), 
  as.character(links$target)) %>% unique()
)
 
# With networkD3, connection must be provided using id, not using real name like in the links dataframe.. So we need to reformat it.
links$IDsource <- match(links$source, nodes$name)-1 
links$IDtarget <- match(links$target, nodes$name)-1
 
# Make the Network
p <- sankeyNetwork(Links = links, Nodes = nodes,
              Source = "IDsource", Target = "IDtarget",
              Value = "value", NodeID = "name", 
              fontSize = 14, fontFamily = 'Arial',
              sinksRight=FALSE)
p

# save the widget
# library(htmlwidgets)
# saveWidget(p, file=paste0( getwd(), "/HtmlWidget/sankeyBasic1.html"))
```

```{r}
URL <- paste0('https://cdn.rawgit.com/christophergandrud/networkD3/',
              'master/JSONdata/energy.json')
energy <- jsonlite::fromJSON(URL)

# Plot
sankeyNetwork(Links = energy$links, Nodes = energy$nodes, Source = 'source',
             Target = 'target', Value = 'value', NodeID = 'name',
             units = 'TWh', fontSize = 12, nodeWidth = 30)

# Colour links
energy$links$energy_type <- sub(' .*', '',
                               energy$nodes[energy$links$source + 1, 'name'])

sankeyNetwork(Links = energy$links, Nodes = energy$nodes, Source = 'source',
             Target = 'target', Value = 'value', NodeID = 'name',
             LinkGroup = 'energy_type', NodeGroup = NULL)

```

