## Supporting Methods

### Analysis grid

All spatial analyses were calculated on a gridded global map using a Mollweide equal-area projection coordinate reference system (CRS), gridded to 10 km x 10 km resolution.  An ocean base map was prepared by rasterizing the vector ocean polygon features of the Natural Earth (https://www.naturalearthdata.com/) Oceans 1:10m dataset to a 1 km x 1 km Mollweide projection, then aggregating by a factor of 10 to approximate percentage of ocean within each cell.  The resulting 10 km Mollweide ocean raster was used as the target raster for projecting all other datasets, and was used to mask out non-ocean cells from reprojected data.

To examine variation in calculations across coastal regions and ecoregions, we prepared two supporting rasters at the same CRS as our analysis grid: coastal area based on cells with a minimum depth less than 200 m, based on GEBCO bathymetry data [@sandwell_BathymetrySpace_2002], and marine ecoregions of the world [@spalding_MarineEcoregions_2007].

### Species distributions

Species distribution data were taken from AquaMaps [@kaschner_AquaMapsPredicted_2019] (n = 18,480) and IUCN species distribution maps [@iucn_IUCNRed_2021; @bli_2018] (n = 2,679).  For both datasets, synonymous scientific binomials and slight differences in nomenclature were resolved by comparing names against accepted names of marine species in the World Register of Marine Species (WoRMS, [@vandepitte_DecadeWorld_2018]) using the `taxize` package [@chamberlain_TaxizeTaxonomic_2013; @chamberlain_TaxizeTaxonomic_2020].  For species appearing in both distribution map datasets, the AquaMaps distribution maps, based on transparent and repeatable algorithms using publicly available data, were preferred over IUCN range maps, which integrate data and expert knowledge but may include mapping decisions that are difficult to replicate.  Each mapping method has advantages and disadvantages, though neither method can perfectly replicate the underlying truth [@rondinini_TradeoffsDifferent_2006].

AquaMaps predicts species ranges as "probability of occurrence" in 0.5° cells, computed based on long-term averages of species-specific relative environmental suitability across multiple environmental variables (temperature, salinity, depth, sea ice concentration, primary production, and in some cases oxygen level and distance to shore) based on species-specific habitat preference derived from publicly available occurrence data [@kaschner_AquaMapsPredicted_2019].  To determine the range map for each species, we converted gradient probabilities into binary presence/absence using a threshold of ≥0.5 to represent "presence" of a given species, following a common practice in conservation literature [e.g., @klein_ShortfallsGlobal_2015; @visalli_DatadrivenApproach_2020; @brito-morales_ClimateVelocity_2020; @hodapp_ClimateChange_2023].  Species maps based on fewer than 10 "occurrence cells" (0.5° cells with at least one validated occurence record) were rejected to ensure quality [@kaschner_AquaMapsPredicted_2019]. These results were then reprojected in raster form to the Mollweide CRS at 10 km resolution, resulting in n = 18,480 species presence maps.  AquaMaps outputs have been validated against independent survey occurrence data and other algorithms often used in species distribution modeling [@ready_PredictingDistributions_2010; @jones_ModellingCommercial_2012]. 

The IUCN dataset presents species ranges as polygons representing the historical, present and possible distribution of a taxon's occurrences [@iucn_IUCNRed_2021].  For each species (or subpopulation where available), we excluded polygons with a "presence" value of 5 indicating "extinct" portions of a range, reprojected the remaining polygon features to the Mollweide CRS, then rasterized the results to the 10 km analysis grid, resulting in n = 2,679 species presence maps.

For coastal and neritic species from both datasets, we masked the resulting presence maps to cells with a minimum depth of 200 m or less using GEBCO bathymetry data [@sandwell_BathymetrySpace_2002], and masked using the ocean area raster to exclude non-ocean cells.  The depth mask for shallow-water species is an effective method of reducing errors of commission in IUCN range maps to better align them with AquaMaps distribution maps [@ohara_AligningMarine_2017].  While AquaMaps uses bottom depth as a parameter to limit ranges for depth-limited species, this masking method allows for a finer resolution map than the 0.5 degree native resolution of AquaMaps. 

### Vulnerability estimates

Vulnerability weights, i.e., relative effect of stressor $j$ on the fitness/health of species $i$, were determined based on methods of Butt et al. [-@butt_TraitbasedFramework_2022].  That study estimated vulnerability of species $i$ to stressor $j$ based on presence of certain traits that are likely to increase the species' physiological sensitivity to the stressor $S_{ij}$, other traits that affect the species' ability to adapt to that specific stressor, i.e., stressor-specific adaptive capacity $A_{ij}$, and life history and population-level traits that affect the population's ability to adapt to or recover from disturbances in general, i.e., general adaptive capacity $G_{i}$.  Traits were binned into nominal or ordinal categories and certain trait values corresponded to different scores for different stressors (see S3 Table).  An additional exposure modifier was included to account for possibility of exposure $E_{ij} \in \{0, 1\}$ of species $i$ to stressor $j$, e.g., a mesopelagic species (depth below 200 m) will not be exposed to ship strikes, so $E_{ij} = 0$.  These metrics were combined to produce a vulnerability score $V_{ij} \in [0, 1]$:

$$V_{ij} = \frac{S_{ij}/S_{ij,max}}{1 + A_{ij}/A_{ij,max} + G_i/G_{i,max}}\times E_{ij}$$

For the present study, we updated some aspects of methodology to improve imputation of species vulnerability for species with partial trait sets.  First, for species whose traits were provided by taxon experts at genus level or higher rank in the trait set assembled by Butt et al. [-@butt_TraitbasedFramework_2022], certain traits (i.e., body length, fecundity, generation time, temperature tolerances, and depth preferences) were filled using species-level data (where available) from FishBase/SealifeBase [@froese_FishBase_2022; @palomares_SeaLifeBase_2022] and AquaMaps [@kaschner_AquaMapsPredicted_2019], while extent of occurrence was determined from the species' distribution map as described above.  Remaining traits were taken as provided by the taxon experts for the original study.  Second, rather than calculate sensitivity, adaptive capacity, and vulnerability scores for species groups then impute missing values based on the distribution of those scores (as done in the original study), we first imputed missing trait values based on frequency within the species' taxonomic neighbors, then scored the sensitivity, adaptive capacity, and vulnerability from the combination of species-level traits (from FishBase, SeaLifeBase, and AquaMaps) and those imputed traits.  Note that these methodological updates resulted in small differences in the vulnerability scores between the published study and our present study: mean/sd difference of .0002 $\pm$ .005, with 98% of differences between -0.00009 and 0.00024.

The expert-elicited trait values used to calculate vulnerability were given as ordinal or nominal categorical values, generally with a single value attributed to each trait for species.  While a single value does not account for large-scale interspecific variability or regional variations in traits, most traits are broadly applicable across a species, genus, or family (e.g., respiration structures of gills vs. lungs vs. diffusion), and for traits representing continuous values (e.g., body size, fecundity, age to maturity), the bins typically increase as orders of magnitude, wide enough to accommodate substantial variation without affecting the vulnerability estimate.

The traits used to calculate sensitivity, adaptive capacity, and exposure components of vulnerability for each stressor are included in S3 Table.  The updated trait-based vulnerability methods and results, including the full matrix translating trait values to vulnerability components and the full dataset of species traits, can be found at https://github.com/mapping-marine-spp-vuln/spp_vuln_framework.

### Uniform exposure stressors

For most of the included stressors, exposure does not depend on species identity (though vulnerability to the stressor certainly might) and therefore we modeled exposure as uniform across all species.  For these stressors, a single map of relative stressor intensity was created from gridded data using the following general process: 

* We reprojected raw intensity to Mollweide CRS at 10 km resolution
* For stressors where marginal impact is expected to be decreasing with intensity (e.g., the hundredth hour of trawling in an area likely overlaps habitat already destroyed by the first hour of trawling), we applied a log transformation to the raw data.
* For stressors whose distribution contains a small number of extreme outliers, we identified a reference point based on the 99.9th percentile; otherwise we assigned a reference point based on the maximum observed value.
* Finally, we rescaled the data using the reference point to result in a distribution of stressor intensity ranging between zero and one.

Information on the data source, transformation, and reference point used for each stressor layer can be found in S4 Table.

### Non-uniform exposure stressors

For several stressors, exposure intensity depends on species-specific information.  These stressors include bycatch, targeted fishing, and sea surface temperature rise.

#### Bycatch stressor

The degree to which species are exposed to bycatch is dependent on their position in the water column.  Pelagic species are unlikely to be swept up in a bottom trawl, while demersal species are unlikely to be swept up in a midwater trawl or purse seine.  We prepared three bycatch layers, summing industrial and nonindustrial discards based on gear type listed by Watson [@watson_DatabaseGlobal_2017] and Watson et al. [@watson_MappingNearly_2018]: 

* Benthic bycatch (affects species identified as benthic), based on gear types: trawl, dredge, and trap
* Pelagic bycatch (affects species identified as pelagic), based on gear types: line (tuna and non-tuna), longline (tuna and non-tuna), midwater trawl, seine, purse seine (tuna and non-tuna), gillnet, other
* Both (affects species identified as benthopelagic or reef-associated): the average of benthic and pelagic bycatch layers.

Catch estimates in Watson [@watson_DatabaseGlobal_2017] and Watson et al. [@watson_MappingNearly_2018] provide data on discards (industrial/non-industrial) by gear type, presented in 0.5° cells.  The discard values were summed across benthic or pelagic gear types, then the totals were normalized by cell ocean area resulting in an intensity of discarded catch, i.e., tonnes of bycatch per square kilometer.  These intensity rasters were reprojected to the 10 km Mollweide CRS analysis grid.  The intensity rasters were then adjusted by dividing by ln(NPP) according to water column position, to indicate that bycatch in a high productivity area is less problematic than the same amount of  bycatch in a low productivity area.

Surface NPP data were taken from Bio-ORACLE [@tyberghein_BioORACLEGlobal_2012; @assis_BioORACLEV2_2018], mean sea surface net primary productivity (NPP) of carbon, g/m^3^/day.

Benthic NPP sums productivity at bottom depth and export flux (e.g., "marine snow") from the surface to bottom depth.  Bottom NPP data were taken from Bio-ORACLE [@tyberghein_BioORACLEGlobal_2012; @assis_BioORACLEV2_2018], mean NPP of carbon at mean bottom depth,  g/m^3^/day.  Export flux from surface to bottom depth were calculated based on an exponential decay model for export flux at depth $d$:

$$f(d) = f_0 \times (1 - r)^{d^{\theta}}$$

Applying non-linear least squares using data from Table 1 (control) in Gt C a^-1^ (globally integrated) in Yool et al [@yool_LowEfficiency_2009], we identified best fit parameters $r = 0.341, \theta = .288$.

Finally, the resulting surface and benthic catch/ln(NPP) layers were rescaled from 0 to 1, using a reference point based on the 99.9% quantile of observed cell values.

#### Targeted fishing stressor

In addition to discards, Watson [@watson_DatabaseGlobal_2017] and Watson et al. [@watson_MappingNearly_2018] report targeted catch for industrial and non-industrial fisheries at 0.5° cells, across multiple gear types and taxonomic groups.  While any species might be vulnerable to targeted fishing, not all species are targeted, and so the targeted fishing stressor layer is distinct for every targeted species (and nonexistent for non-targeted species), thus a targeted fishing stressor layer was calculated separately for each species with non-zero catch in the Watson dataset.

Taxon names were compared to accepted names per WoRMS [@vandepitte_DecadeWorld_2018] using the `taxize` package [@chamberlain_TaxizeTaxonomic_2013; @chamberlain_TaxizeTaxonomic_2020] to resolve synonyms and differences in spelling.  Total catch for each taxon was summed across pelagic gears and benthic gears separately, then divided by cell ocean area resulting in intensity, i.e., tonnes of catch per km^2^.
Catch reported at the species level was attributed directly to that species.  Catch in a given cell but reported at higher ranks (e.g., genus, family) was divided equally among all local species (per species distributions) in that genus or family.  In many cases, a given species would be attributed catch at multiple taxonomic levels in the same cell, which were summed to create a cell total catch intensity for each species, separately for pelagic and benthic gear types.  The pelagic and benthic catch intensities were reprojected to the 10 km Mollweide CRS analysis grid, and then normalized by ln(NPP), either surface or benthic as appropriate, to account for the fact that a unit of catch in a highly productive region imposes less stress on an ecosystem than the same unit of catch in a low-productivity region.  The pelagic and benthic NPP-normalized catch were then summed for each cell for the species.

Reference points to rescale the targeted fishing stressor layers are species specific.  A global maximum reference point was set by first calculating the 90th percentile of NPP-normalized catch for each species across its entire distribution, then selecting the score of the species with the highest 90th percentile value: _Engraulis ringens_, Peruvian anchoveta, at $C_{ref}$ = 2,170 tonnes of NPP-normalized catch.  This global reference point was used to rescale (from 0 to 1) any species whose 99.9th percentile of NPP-normalized catch exceeded this value (15 species total).  For species whose 99.9th percentile catch across its range falls below this reference point, we used the 99.9th percentile of that species' catch across its range as its own reference point.  The reference catch for species $i$ is therefore:

$$C_{ref}^i = \min (C_{ref}, C^i_{99.9\%})$$

The NPP-normalized catch was then rescaled using the appropriate reference point, with values capped at 1.0, resulting in a gridded map of stressor values from 0 to 1 for every species with non-zero targeted catch.

#### SST rise stressor

We included two stressors related to ocean temperature: sea surface temperature extremes, representing impacts from short-lived (weeks to months) high temperature events, i.e., marine heat waves; and rise in annual mean sea surface temperature representing long-term (years to decades) changes in sea surface temperature relative to a historic baseline.  The SST extremes stressor is described above in the uniform-exposure stressors.  Exposure to long-term SST rise estimates the impact to a species when mean annual temperatures risk exceeding the physiological tolerance of the species due to the climatic shift from historic norms in a given location.  For species included in the AquaMaps dataset, we used the thermal preference envelope used to generate species distributions; for species included in IUCN but not AquaMaps, we generated thermal preference envelopes (absolute and preferred minimum and maximum temperatures) in a manner similar to that used to generate envelopes for AquaMaps, using observed mean annual temperature in cells across the species distribution according to IUCN distribution maps: 

* $T_{min}^{a}$ = (25th percentile - 1.5 × interquartile) or absolute minimum mean annual temperature (whichever is lesser)
* $T_{max}^{a}$ = 75th percentile + 1.5 × interquartile or absolute maximum mean annual temperature (whichever is greater)
* $T_{min}^{p}$ = 10th percentile of observed variation in mean annual temperature
* $T_{max}^{p}$ = 90th percentile of observed variation in mean annual temperature

We modeled physiological thermal stressor intensity $s_T$ for each species based on the local mean annual temperature $\bar T$ relative to its preferred and absolute thermal range:

$$s_T = \begin{cases}
  0 &\text{where }\bar T \leq T_{max}^{p}\\
  \frac{\bar T - T_{max}^{p}}{T_{max}^a - T_{max}^p} &\text{where }T_{max}^{p} < \bar T < T_{max}^{a}\\
  1 &\text{where }\bar T \geq T_{max}^{p}
\end{cases}$$

For each species, mean annual temperature from [@cortad6_2020] in each pixel across its distribution was compared to the thermal preferences according to the above formula to generate a species-specific map of thermal stressor intensity.  Note that species whose minimum depth preference was deeper than 200 meters (i.e., not epipelagic) were assigned a value of zero for this stressor.

### Stressor layers for habitat method

Stressor layers for the Habitat Method of calculating cumulative human impact included all the same uniform exposure stressor layers used for the species and functional entity methods.  See S4 Table for details on transformations and rescaling.  

Species-specific stressor layers (SST rise stressor based on species thermal tolerance, targeted fishing based on species identity, benthic and pelagic bycatch based on position in the water column) could not be included in the same manner as for the species approach, as those calculations depended on species-specific information that cannot be broadly applied at the representative habitat level.  However, fisheries pressures (targeted and bycatch) were accounted for by creating layers from the same source, i.e., Watson [-@watson_DatabaseGlobal_2017], in the same manner as described in Halpern et al. [-@halpern_RecentPace_2019]. These new layers were aggregated by method, depth, and scale:  commercial pelagic and demersal low bycatch, commercial pelagic high bycatch, commercial demersal destructive, and artisanal/small scale fishing.  For all these categories, overall fishing intensity (catch per km^2^) was normalized by ln(NPP), then rescaled to the 99.9% quantile across all years for that catch category, resulting in stressor scores from 0 to 1.  See S4 Table for details on transformations and rescaling.

### Habitat maps for habitat method

Habitat maps prepared for Halpern et al. [-@halpern_RecentPace_2019], at 934 m resolution in a Mollweide equal area coordinate reference system, were aggregated by a factor of 11 (to identify habitat density at approximately 10 km resolution) then reprojected to match our analysis grid.  Corals and seagrass layers were based on habitat maps updated for Berger et al. [-@berger_SourcesDischarge_2022].  Kelp and saltmarsh layers were based on maps updated for the Ocean Health Index 2021.  


### Functional entities

We assigned species to functional entities based on categorical values of four traits (maximum body length, adult mobility, water column position, adult trophic level) that roughly gather species into similar niche space, following Mouillot et al. [-@mouillot_FunctionalOverredundancy_2014].  Out of 512 possible functional entities (8 body length categories × 4 adult mobility categories × 4 water column position × 4 trophic level categories = 512 unique combinations of trait values), 339 contained at least one species within our set (min: 1 species; max: 1034 species; mean: 63.59; median: 19).  Due to limited trait data available across a broad range of taxa, our analysis relied on a smaller set of traits for assignment of functional entity than Mouillot et al. [-@mouillot_FunctionalOverredundancy_2014], which results in fewer but more populous functional entities and therefore a more conservative estimate of functional vulnerability.

Trait values were gleaned from [@butt_TraitbasedFramework_2022; @froese_FishBase_2022; @palomares_SeaLifeBase_2022]; missing values were imputed using Multiple Imputation by Chained Equation (MICE) in the R package `mice` [@vanbuuren_MiceMultivariate_2011] using all other traits plus fecundity (where available), generation time (where available), order, and family.  S7 Fig. shows missingness of traits that were gapfilled.

#### Maximum body length

Values of maximum total length (in cm) were determined from sources: [@butt_TraitbasedFramework_2022; @froese_FishBase_2022; @palomares_SeaLifeBase_2022]

* (0, 1.5]
* (1.5, 7.0]
* (7, 15]
* (15, 30]
* (30, 50]
* (50, 80]
* (80, 150]
* (150, ...)

For categorizing maximum body length, we largely relied on the same values as Mouillot et al. [-@mouillot_FunctionalOverredundancy_2014], adding a bin on either end to capture the wider range of values possible in our set of species.

#### Adult mobility

Values were determined from sources: [@butt_TraitbasedFramework_2022]

* Sessile
* Sedentary
* Mobile resident
* Migratory/nomadic

#### Water column position

Values were determined from sources: [@butt_TraitbasedFramework_2022; @froese_FishBase_2022; @palomares_SeaLifeBase_2022]

* Benthic
* Benthopelagic
* Pelagic
* Reef-associated

#### Adult trophic level

Values were determined from sources: [@froese_FishBase_2022; @palomares_SeaLifeBase_2022]

* Primary consumer: (1, 2]
* Secondary consumer: (2, 3]
* Tertiary consumer: (3, 4]
* Apex consumer: (4, ...)

### Sensitivity analysis: trait selection

To test the sensitivity of the functional entity approach to variation in assignment of trait values, we chose a random sample of 100,000 cells and subjected the species compositions in each cell to a Monte Carlo simulation of trait values. For each trait used to identify functional entity membership (maximum body length, adult trophic level, adult mobility, and water column position), trait values within each cell were resampled with replacement (holding the other three traits constant) and reassigned to the species within the cell. Based on the reassigned trait values, species were regrouped into new functional entities, and the functional vulnerability calculation was performed on this new set.  The resample procedure was performed 1000 times for each trait, with a unique pseudorandom seed assigned to each simulation to ensure reproducibility.

From the 1000 simulations for each trait, summary statistics (mean, std deviation, 95% confidence interval) were calculated for functional vulnerability.  The difference between the simulated mean and the base calculation is shown in S6 Fig. (A-D). The randomly resampling and reassigning of trait values results in novel trait combinations not likely to be found in nature, resulting in more low-membership functional entities, and thus increasing the average functional vulnerability across the simulated community (mean 0.037, std dev 0.040).

To measure the effect of trait variation on cumulative impact, we calculated the cumulative impact according to the functional entity method on each simulated community.  Note that while some of these traits were used to estimate a species' vulnerability to a stressor, we did not recalculate the species-stressor vulnerability score here, only the functional entity membership.  The difference between the simulated mean cumulative impact and the base calculation is shown in S6 Fig. (E-H).  Even considering the slightly elevated functional vulnerability, the difference in cumulative impact was quite small (mean -0.0026, std dev 0.019).

### R code and packages

All analysis was performed in R statistical software, version 4.0.4 [@rcoreteam_LanguageEnvironment_2022], relying primarily on packages `tidyverse` [@wickham_WelcomeTidyverse_2019], `terra` [@hijmans_TerraSpatial_2022], `sf` [@pebesma_SimpleFeatures_2018], `taxize` [@chamberlain_TaxizeTaxonomic_2013; @chamberlain_TaxizeTaxonomic_2020], `rfishbase` [@boettiger_RfishbaseExploring_2012].

All data used as inputs for this assessment are freely available from original sources.  All original code and data resulting from this analysis has been deposited at [Figshare](https://figshare.com/) and is publicly available as of the date of publication at DOI:10.6084/m9.figshare.26454106.  A living version of the code and data can be found at https://github.com/mapping-marine-spp-vuln/spp_vuln_mapping.
